import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.scss";
import { NavBar } from "@/components";
import { ConfigProvider } from "antd";
import { antdTheme } from "@/styles/antDesign.theme";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ConfigProvider theme={antdTheme}>

          <NavBar />
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
